---
mqtt:
  broker: tcp://mosquitto.internal.k8s.vogelherdweg.de:1883
  rootTopic: lcn
  enabled: true

serial:
  port: /dev/ttyUSB0
  baudRate: 9600

logger:
  development: true
  disableCaller: false
  disableStacktrace: false
  encoding: console
  level: info

