name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Tidy check
      run: make tidy

    - name: Build
      run: make build

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Build Docker image
      run: make docker-build

